WITH CTE AS(
SELECT *,LAG(current_year_spend) OVER(PARTITION BY PRODUCT_ID) AS PREV_YEAR_SPEND
FROM (
SELECT EXTRACT(YEAR FROM TRANSACTION_DATE) AS YEAR,PRODUCT_ID,SPEND AS CURRENT_YEAR_SPEND
FROM user_transactions)S)
SELECT *, ROUND((CURRENT_YEAR_SPEND-prev_year_spend)/prev_year_spend*100,2) AS yOY_RATE
FROM CTE